var JaySongsheet = [
    {
        "title":"Mojito",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL001.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWr5l.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL001.lrc"
    },{
        "title":"Try",
        "author":"派伟俊 / 周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL002.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWy1K.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL002.lrc"
    },{
        "title":"爱在西元前",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL003.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW7pP.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL003.lrc"
    },{
        "title":"本草纲目",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL004.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWm8S.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL004.lrc"
    },{
        "title":"不能说的秘密",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL005.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW4Bi.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL005.lrc"
    },{
        "title":"彩虹",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL006.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW1k6.md.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL006.lrc"
    },{
        "title":"稻香",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL007.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWNfb.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL007.lrc"
    },{
        "title":"东风破",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL008.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWPpC.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL008.lrc"
    },{
        "title":"发如雪",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL009.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWK0B.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL009.lrc"
    },{
        "title":"告白气球",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL010.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWhDD.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL010.lrc"
    },{
        "title":"公主病",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL011.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWgHa.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL011.lrc"
    },{
        "title":"花海",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL012.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWNfb.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL012.lrc"
    },{
        "title":"黄金甲",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL013.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWFnI.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL013.lrc"
    },{
        "title":"霍元甲",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL014.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWJxN.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL014.lrc"
    },{
        "title":"简单爱",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL015.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW7pP.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL015.lrc"
    },{
        "title":"菊花台",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL016.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWm8S.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL016.lrc"
    },{
        "title":"兰亭序",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL017.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWNfb.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL017.lrc"
    },{
        "title":"龙卷风",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL018.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWxw1.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL018.lrc"
    },{
        "title":"迷迭香",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL019.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWxw1.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL019.lrc"
    },{
        "title":"牛仔很忙",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL020.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW1k6.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL020.lrc"
    },{
        "title":"蒲公英的约定",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL021.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW1k6.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL021.lrc"
    },{
        "title":"千里之外",
        "author":"周杰伦 / 费玉清",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL022.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWm8S.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL022.lrc"
    },{
        "title":"千山万水",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL023.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWkSG.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL023.lrc"
    },{
        "title":"七里香",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL024.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWi8F.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL024.lrc"
    },{
        "title":"青花瓷",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL025.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW1k6.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL025.lrc"
    },{
        "title":"晴天",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL026.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWPpC.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL026.lrc"
    },{
        "title":"三年二班",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL027.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWPpC.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL027.lrc"
    },{
        "title":"珊瑚海",
        "author":"周杰伦 / Lara梁心颐",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL028.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWK0B.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL028.lrc"
    },{
        "title":"双截棍",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL029.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW7pP.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL029.lrc"
    },{
        "title":"算什么男人",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL030.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWZws.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL030.lrc"
    },{
        "title":"甜甜的",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL031.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dW1k6.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL031.lrc"
    },{
        "title":"听爸爸的话",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL032.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWZws.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL032.lrc"
    },{
        "title":"听妈妈的话",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL033.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWm8S.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL033.lrc"
    },{
        "title":"烟花易冷",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL034.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWRfL.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL034.lrc"
    },{
        "title":"夜的第七章",
        "author":"周杰伦 / 潘儿",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL035.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWm8S.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL035.lrc"
    },{
        "title":"夜曲",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL036.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWK0B.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL036.lrc"
    },{
        "title":"一口气全念对",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL037.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWZws.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL037.lrc"
    },{
        "title":"一路向北",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL038.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWK0B.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL038.lrc"
    },{
        "title":"最伟大的作品",
        "author":"周杰伦",
        "url":"https://githubdrive.gavin-chen.top/Music/audio/ZJL039.mp3",
        "pic":"https://blog-hexo-img.oss-cn-shanghai.aliyuncs.com/dWAKg.webp",
        "lrc":"https://githubdrive.gavin-chen.top/Music/lrc/ZJL039.lrc"
    }
];

WIDGET = {
    "CONFIG": {
        "modules": "0124",
        "background": "5",
        "tmpColor": "var(--font-color)",
        "tmpSize": "16",
        "cityColor": "var(--font-color)",
        "citySize": "16",
        "aqiColor": "var(--font-color)",
        "aqiSize": "16",
        "weatherIconSize": "24",
        "alertIconSize": "18",
        "padding": "10px 0px",
        "shadow": "0",
        "language": "auto",
        "fixed": "false",
        "vertical": "top",
        "horizontal": "left",
        "key": "c364314f2dc349ffae8fda8e6c9cd06c"
    }
}