var JaySongsheet = [
    {
        "title": "Mojito",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL001.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWr5l.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL001.lrc"
    }, {
        "title": "Try",
        "author": "派伟俊 / 周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL002.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWy1K.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL002.lrc"
    }, {
        "title": "爱在西元前",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL003.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW7pP.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL003.lrc"
    }, {
        "title": "本草纲目",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL004.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWm8S.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL004.lrc"
    }, {
        "title": "不能说的秘密",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL005.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW4Bi.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL005.lrc"
    }, {
        "title": "彩虹",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL006.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW1k6.md.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL006.lrc"
    }, {
        "title": "稻香",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL007.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWNfb.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL007.lrc"
    }, {
        "title": "东风破",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL008.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWPpC.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL008.lrc"
    }, {
        "title": "发如雪",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL009.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWK0B.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL009.lrc"
    }, {
        "title": "告白气球",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL010.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWhDD.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL010.lrc"
    }, {
        "title": "公主病",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL011.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWgHa.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL011.lrc"
    }, {
        "title": "花海",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL012.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWNfb.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL012.lrc"
    }, {
        "title": "黄金甲",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL013.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWFnI.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL013.lrc"
    }, {
        "title": "霍元甲",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL014.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWJxN.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL014.lrc"
    }, {
        "title": "简单爱",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL015.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW7pP.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL015.lrc"
    }, {
        "title": "菊花台",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL016.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWm8S.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL016.lrc"
    }, {
        "title": "兰亭序",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL017.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWNfb.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL017.lrc"
    }, {
        "title": "龙卷风",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL018.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWxw1.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL018.lrc"
    }, {
        "title": "迷迭香",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL019.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWxw1.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL019.lrc"
    }, {
        "title": "牛仔很忙",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL020.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW1k6.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL020.lrc"
    }, {
        "title": "蒲公英的约定",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL021.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW1k6.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL021.lrc"
    }, {
        "title": "千里之外",
        "author": "周杰伦 / 费玉清",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL022.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWm8S.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL022.lrc"
    }, {
        "title": "千山万水",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL023.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWkSG.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL023.lrc"
    }, {
        "title": "七里香",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL024.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWi8F.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL024.lrc"
    }, {
        "title": "青花瓷",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL025.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW1k6.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL025.lrc"
    }, {
        "title": "晴天",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL026.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWPpC.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL026.lrc"
    }, {
        "title": "三年二班",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL027.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWPpC.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL027.lrc"
    }, {
        "title": "珊瑚海",
        "author": "周杰伦 / Lara梁心颐",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL028.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWK0B.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL028.lrc"
    }, {
        "title": "双截棍",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL029.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW7pP.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL029.lrc"
    }, {
        "title": "算什么男人",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL030.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWZws.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL030.lrc"
    }, {
        "title": "甜甜的",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL031.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dW1k6.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL031.lrc"
    }, {
        "title": "听爸爸的话",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL032.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWZws.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL032.lrc"
    }, {
        "title": "听妈妈的话",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL033.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWm8S.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL033.lrc"
    }, {
        "title": "烟花易冷",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL034.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWRfL.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL034.lrc"
    }, {
        "title": "夜的第七章",
        "author": "周杰伦 / 潘儿",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL035.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWm8S.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL035.lrc"
    }, {
        "title": "夜曲",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL036.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWK0B.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL036.lrc"
    }, {
        "title": "一口气全念对",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL037.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWZws.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL037.lrc"
    }, {
        "title": "一路向北",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL038.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWK0B.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL038.lrc"
    }, {
        "title": "最伟大的作品",
        "author": "周杰伦",
        "url": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/audio/ZJL039.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/cover/dWAKg.webp",
        "lrc": "https://cdn.cbd.int/cansin-music-jaychou@1.0.0/lrc/ZJL039.lrc"
    }
];

var QianSongsheet = [
    {
        "title": "银河少年",
        "author": "王啸坤 / 薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/银河少年.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/银河少年.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/银河少年.lrc"
    }, {
        "title": "老街",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/老街.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/老街.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/老街.lrc"
    }, {
        "title": "戒烟",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/戒烟.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/戒烟.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/戒烟.lrc"
    }, {
        "title": "潘金莲",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/潘金莲.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/潘金莲.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/潘金莲.lrc"
    }, {
        "title": "野心",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/野心.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/野心.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/野心.lrc"
    }, {
        "title": "聊表心意",
        "author": "薛之谦 / 刘惜君",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/聊表心意.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/聊表心意.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/聊表心意.lrc"
    }, {
        "title": "木偶人",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/木偶人.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/木偶人.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/木偶人.lrc"
    }, {
        "title": "天外来物",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/天外来物.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/天外来物.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/天外来物.lrc"
    }, {
        "title": "耗尽",
        "author": "薛之谦 / 郭聪明",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/耗尽.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/耗尽.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/耗尽.lrc"
    }, {
        "title": "作曲家",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/作曲家.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/作曲家.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/作曲家.lrc"
    }, {
        "title": "李白",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/李白.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/李白.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/李白.lrc"
    }, {
        "title": "喜剧之王",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/喜剧之王.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/喜剧之王.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/喜剧之王.lrc"
    }, {
        "title": "年少有为",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/年少有为.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/年少有为.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/年少有为.lrc"
    }, {
        "title": "麻雀",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/麻雀.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/麻雀.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/麻雀.lrc"
    }, {
        "title": "爸爸妈妈",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/爸爸妈妈.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/爸爸妈妈.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/爸爸妈妈.lrc"
    }, {
        "title": "不将就",
        "author": "李荣浩",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/不将就.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/不将就.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/不将就.lrc"
    }, {
        "title": "陪你去流浪",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/陪你去流浪.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/陪你去流浪.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/陪你去流浪.lrc"
    }, {
        "title": "摩天大楼",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/摩天大楼.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/摩天大楼.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/摩天大楼.lrc"
    }, {
        "title": "来日方长",
        "author": "薛之谦 / 黄龄",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/来日方长.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/来日方长.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/来日方长.lrc"
    }, {
        "title": "我害怕",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/我害怕.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/我害怕.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/我害怕.lrc"
    }, {
        "title": "像风一样",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/像风一样.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/像风一样.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/像风一样.lrc"
    }, {
        "title": "慢半拍",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/慢半拍.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/慢半拍.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/慢半拍.lrc"
    }, {
        "title": "天后 (Live)",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/天后 (Live).mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/天后 (Live).jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/天后 (Live).lrc"
    }, {
        "title": "怪咖",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/怪咖.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/怪咖.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/怪咖.lrc"
    }, {
        "title": "肆无忌惮",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/肆无忌惮.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/肆无忌惮.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/肆无忌惮.lrc"
    }, {
        "title": "几个你",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/几个你.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/几个你.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/几个你.lrc"
    }, {
        "title": "有没有",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/有没有.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/有没有.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/有没有.lrc"
    }, {
        "title": "方圆几里",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/方圆几里.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/方圆几里.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/方圆几里.lrc"
    }, {
        "title": "那是你离开了北京的生活",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/那是你离开了北京的生活.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/那是你离开了北京的生活.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/那是你离开了北京的生活.lrc"
    }, {
        "title": "花儿和少年",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/花儿和少年.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/花儿和少年.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/花儿和少年.lrc"
    }, {
        "title": "一半",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/一半.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/一半.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/一半.lrc"
    }, {
        "title": "哑巴",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/哑巴.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/哑巴.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/哑巴.lrc"
    }, {
        "title": "消愁",
        "author": "薛之谦的毛不易啊",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/消愁.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/消愁.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/消愁.lrc"
    }, {
        "title": "初学者",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/初学者.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/初学者.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/初学者.lrc"
    }, {
        "title": "下雨了",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/下雨了.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/下雨了.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/下雨了.lrc"
    }, {
        "title": "狐狸",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/狐狸.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/狐狸.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/狐狸.lrc"
    }, {
        "title": "认真的雪",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/认真的雪.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/认真的雪.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/认真的雪.lrc"
    }, {
        "title": "我知道你都知道",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/我知道你都知道.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/我知道你都知道.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/我知道你都知道.lrc"
    }, {
        "title": "动物世界",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/动物世界.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/动物世界.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/动物世界.lrc"
    }, {
        "title": "暧昧",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/暧昧.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/暧昧.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/暧昧.lrc"
    }, {
        "title": "意外",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/意外.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/意外.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/意外.lrc"
    }, {
        "title": "绅士",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/绅士.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/绅士.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/绅士.lrc"
    }, {
        "title": "说谎 (Live)",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/audio/说谎 (Live).mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/cover/说谎 (Live).jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue2@1.0.0/lrc/说谎 (Live).lrc"
    }, {
        "title": "违背的青春",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/违背的青春.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/违背的青春.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/违背的青春.lrc"
    }, {
        "title": "你还要我怎样",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/你还要我怎样.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/你还要我怎样.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/你还要我怎样.lrc"
    }, {
        "title": "演员",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/演员.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/演员.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/演员.lrc"
    }, {
        "title": "刚刚好",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/刚刚好.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/刚刚好.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/刚刚好.lrc"
    }, {
        "title": "我好像在哪见过你",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/我好像在哪见过你.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/我好像在哪见过你.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/我好像在哪见过你.lrc"
    }, {
        "title": "丑八怪",
        "author": "薛之谦",
        "url": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/audio/丑八怪.mp3",
        "pic": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/cover/丑八怪.jpg",
        "lrc": "https://cdn.cbd.int/cansin-music-jackyxue1@1.0.0/lrc/丑八怪.lrc"
    }
];